CREATE TABLE PARSEDATA  (
	KEYWORDS TEXT,
	url TEXT,
	title TEXT,
	SOURCE TEXT,
	CREATE_TIME DATE,
	UPDATE_TIME DATE
);

CREATE TABLE BASEDATA  (
	KEYWORDS TEXT,
	url TEXT,
	title TEXT,
	SOURCE TEXT,
	CREATE_TIME DATE,
	UPDATE_TIME DATE
);